org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.builtInKotlin=false
org.gradle.daemon.idletimeout=3600000
android.experimental.privacysandbox.enable=false
android.experimental.baselineprofiles.enable=false
android.baselineprofile.skipgeneration=true
android.enableBaselineProfileExtraction=false
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
SUPABASE_URL="https://hflcacrgwxszejlkcxsh.supabase.co"
SUPABASE_ANON_KEY="sb_publishable_JmQBsLcvMBc-vFn0-lAXIg_3pQLaip7"