@echo off
title Reiniciando CuevanaTV...
echo Matando procesos de Node existentes...
taskkill /F /IM node.exe /T >nul 2>&1
echo Esperando liberacion de puertos...
timeout /t 2 /nobreak >nul
echo Iniciando Servidor de Sincronizacion...
start powershell.exe -NoExit -Command "cd 'D:\magik\Mi app\Cuevanatv\scripts'; node sync_api_server.mjs"
echo Iniciando Admin Panel...
start powershell.exe -NoExit -Command "cd 'D:\magik\Mi app\Cuevanatv\admin-panel'; npm run dev"
echo ¡Ecosistema iniciado correctamente!
timeout /t 3 /nobreak >nul
exit
